# Generated by Django 5.2 on 2025-05-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('pcategory', models.CharField(max_length=50)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
