# Generated by Django 5.2 on 2025-05-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_products_pimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('pcategory', models.CharField(max_length=50)),
                ('quatity', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=0)),
            ],
        ),
    ]
