# Generated by Django 5.2 on 2025-05-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pimages',
            field=models.ImageField(default=1, upload_to='uploads', verbose_name='Default.jpg'),
            preserve_default=False,
        ),
    ]
